/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EditDelete;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author M NJERIC
 */
public class PanalAction extends javax.swing.JPanel {

    /**
     * Creates new form PanalAction
     */
    public PanalAction() {
        initComponents();
    }
    
    ///////////for edit
    public void intevent(TableActionEvent event,int row){
        cmdedit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.edit(row);  
            }
        });
        
        ////for delete
        cmddelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.delete(row);
                
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdedit = new javax.swing.JButton();
        cmddelete = new javax.swing.JButton();

        cmdedit.setBackground(new java.awt.Color(153, 153, 255));
        cmdedit.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cmdedit.setText("Edit");
        cmdedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditActionPerformed(evt);
            }
        });

        cmddelete.setBackground(new java.awt.Color(255, 102, 102));
        cmddelete.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cmddelete.setText("Delete");
        cmddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cmddelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdedit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cmdedit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cmddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdeditActionPerformed

    private void cmddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmddeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmddelete;
    private javax.swing.JButton cmdedit;
    // End of variables declaration//GEN-END:variables
}
